require("config.options")
require("config.autocmds")
require("config.lsp")
require("config.completion")
require("config.keymaps")

require("plugins.colorscheme")
require("plugins.syntax-parser")
require("plugins.lsp-config")
-- require("plugins.completion")
require("plugins.fuzzy-find")
require("plugins.binaries")
require("plugins.formatting")
require("plugins.debugging")
require("plugins.ai")
require("plugins.preview")

vim.cmd("packadd cfilter")
